-- 코드를 입력하세요
SELECT PRODUCT_CODE,SUM(P.PRICE * SALES_AMOUNT) as 'SALES'
from PRODUCT P 
inner join OFFLINE_SALE S
on P.PRODUCT_ID = S.PRODUCT_ID
group by PRODUCT_CODE
order by SALES desc, PRODUCT_CODE